# Generated by Django 5.2.11 on 2026-02-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
