# Generated by Django 5.2.11 on 2026-02-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='logo',
        ),
    ]
