# Generated by Django 5.2.11 on 2026-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_skill_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('credential_link', models.URLField(blank=True)),
            ],
        ),
    ]
