# Generated by Django 5.2.11 on 2026-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
